### ISSUE TITLE
Every Door users produce piles of amenity=fixme

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/every_door#880]
If Every Door presets make impossible to enter some POI then opening note with a photo, opening note or no entering anything would be preferable over `amenity=fixme` with cryptic unclear descriptions

![Image](https://github.com/user-attachments/assets/8e04e9fd-d6aa-46d7-b3f3-ef473daa0b69)

I tried fixing some and in most cases it ended in writing changeset comments on edits that added them asking for more info

**Comment by matkoniecz** [comment]
for more actionable things: would it be possible to create notes rather than this cryptic `amenity=fixme` ?

preferably notes with photos?

**Comment by deevroman** [comment]
Creating a POI has an advantage over taking notes: you can specify general information in the POI card, such as address, floor, accessibility, ....

Therefore, it would be better to create amenity=fixme + note

**Comment by matkoniecz** [comment]
> address, floor, accessibility, ....

you can specify this also in note

**Comment by matkoniecz** [comment]
> All you need in the case of amenity=fixme is to find in the correct tag in wiki

I tried that, in vast majority of cases you have not enough info

with notes it is much easier to gather extra info or close unclear ones

> But why this extra work?

to convert more incomplete and unclear survey notes into something useful

**Comment by matkoniecz** [comment]
Also, notes are much easier to notice by people interested in processing reports like this - with robust system of various tools.

**Comment by Zverik** [comment]
First, having those fixme's as amenities makes it possible to record all the tags, and convert it later easier — instead of copying text from notes, which I believe hardly anyone does.

It's pretty easy to find examples where it helps: https://www.openstreetmap.org/node/10908598139/history

Most mappers outside Every Door just use nonsensical tags like shop=yes, which are harder to spot and to fix. The main benefit of having "amenity=fixme" is that it is so easy to find, to measure, and potentially fix those. Having those as notes would mix them with other notes for other kinds of things, and definitely _not_ make fixing those easier.

Also OSM browsers don't display amenity=fixme, so it doesn't create any more issues than millions of AI buildings, or access=unknown, or highway=road, or 200 thousand of shop=yes.

**Comment by matkoniecz** [comment]
> just use nonsensical tags like shop=yes, which are harder to spot and to fix

actually amenity=fixme is worse - it is added to anything from shops of unspecific type (migrated one to shop=yes in https://www.openstreetmap.org/node/12480437386/history ), missing footways ( one fixed to https://www.openstreetmap.org/changeset/163858591 ) and things that definitely should be note ( I fixed for example https://www.openstreetmap.org/node/12022637776/history )

at least with `shop=yes` you know that it is shop of unspecific type (and this for example gets a dedicated quest in StreetComplete)

`amenity=fixme` mixes shops of unspecific type, missing footways, reports of duplicated restaurants, and completely unclear notes and just incomprehensible notes ( https://www.openstreetmap.org/node/11055596258 ) and more


> Having those as notes would mix them with other notes for other kinds of things, and definitely not make fixing those easier.

As someone who processed over 14 000 notes and also large number of fixme and weirdly tagged objects: no, it does not

making notes for notes actually makes easier to process notes, rather than creating incomplete objects in a brand new tagging schema incompatible with all tooling existing to support notes

**Comment by matkoniecz** [comment]
Every Door should at least guide users to not create `amenity=fixme` POIs about things like duplicated restaurants, missing footways.

And ask them to provide enough info so that this notes saved as POIs are comprehensible.

**Comment by deevroman** [comment]
I think if you change the current behavior, then after implementation https://github.com/Zverik/every_door/issues/184

I also resolve notes and I can say that even if you fill out the form like onosm.org, I still don't want to remember which tags I should fill in. Unless you write in the note right away in the form: `key=value\n ...`

**Comment by matkoniecz** [comment]
onosm.org notes are utterly useless, though this is a separate problem (my bot account closed hundreds of onosm.org notes misplaced at Iran place=country node...)

> Only if you write the note in the format: `key=value\n ...`

and it seems 100% fine to format them this way

**Comment by Zverik** [comment]
I can do a half-way remedy: convert nodes with amenity=fixme to notes, but only those that have at most a name entered. Any specific tag, like opening hours, and it keeps being an amenity.

Also I consider shop=yes to be an error, unlike amenity=fixme.

**Comment by matkoniecz** [comment]
> Also I consider shop=yes to be an error, unlike amenity=fixme.

why amenity=fixme would not be an error?

it is 100% definitely wrong tag that requires fixing (and in ED use it does not even distinguish between "shop of unknown type" and "missing footway")

**Comment by Woazboat** [comment]
`amenity=fixme` is a troll tag that's even worse than `shop=vacant`.
'Fixme' is not a type of amenity and shouldn't be in the amenity namespace, _especially_ if it just serves as a placeholder/note for something that isn't even an `amenity=*`.

Using `<key>=yes` as a generic 'this is a `<key>`, but the exact type is not specified' is widely used in OSM, so `shop=yes` is valid for mapping shops where the exact shop type cannot be specified at the time.

**Comment by matkoniecz** [comment]
> amenity=fixme is a troll tag that's even worse than shop=vacant.

as someone who invented term troll tag I would say that it is not one as far as https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35702 tried to define it - it does not redefine other tags

**Comment by Woazboat** [comment]
Okay, it's not a troll tag in the https://wiki.openstreetmap.org/wiki/Trolltag / https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35702 sense. However I'd argue that the difference is minimal since it has pretty much the same effect, just with the tag _key_ instead of another tag.

`amenity=not_an_amenity`

vs.

`amenity=foo`
`exists=no`

**Comment by mnalis** [comment]
> for more actionable things: would it be possible to create notes rather than this cryptic `amenity=fixme` ?
> preferably notes with photos?

I agree  with that! 

BTW, how does one even create those `amenity=fixme` in ED? I've tried in amenity mode adding a node and searching for "fixme", but it didn't find anything. And it seems to be common thing (judging by growth in that graph), so it is probably even simpler than that - but I don't see it?

> Most mappers outside Every Door just use nonsensical tags like `shop=yes`, which are harder to spot and to fix. The main benefit of having "amenity=fixme"

I fail to see how searching for one string is harder then searching for another string? Also, `shop=yes` is hardly [nonsensical](https://en.wiktionary.org/wiki/nonsensical). It says _"yes, there is a shop here"_ (just like e.g. `covered=yes` says _"yes, it is covered here"_). It is lacking in details, sure, but that is whole point, right? (that you cannot chose correct type at the moment).

So if I was truly unable to better describe that shop at the spot, I'd add `shop=yes` + `description=*` (and/or `fixme=*`) which describes in details what it is. That would also allow to record the details like card payment, webpage, etc. Or I'd leave a Note with explanation (and preferably pictures) of all of those, so some armchair mapper could do it.

> It's pretty easy to find examples where it helps: https://www.openstreetmap.org/node/10908598139/history

Ummm, how did it help exactly? It was `shop=yes`  previously so we've at least known it is some type of a **shop**, and then that was removed and replaced with `amenity=fixme` (which could be `amenity=waste_basket` or  `amenity=post_box` for all we know?), so IMHO that sounds like a loss of information by itself.

Also, is that `amenity=fixme` + `fixme=type` + `fixme:type=baker_products` node supposed to be in its best (final) form? Or is it intended to be improved, e.g. if someone can capture a few photos of what it sells? Because, if it can be improved by adding notes with pictures, why not do that in the first place?

For that particular example, I'd probably just tag it (if automatic translator or `description` field is accurate) as  [shop=party](https://wiki.openstreetmap.org/wiki/Tag:shop=party) if that is what it is primarily about, and maybe add a `fixme` or `note` saying that it also sells confectionery (judging from description) and maybe cakes (just guessing from `fixme:type=baker_products`?). 

Or, If it really was important, I'd tag it as a three (very close) separate nodes with same `name`, one as  [shop=party](https://wiki.openstreetmap.org/wiki/Tag:shop=party), one as [shop=confectionery](https://wiki.openstreetmap.org/wiki/Tag:shop=confectionery) , and one as [shop=pastry](https://wiki.openstreetmap.org/wiki/Tag:shop=pastry) (or [shop=bakery](https://wiki.openstreetmap.org/wiki/Tag:shop=bakery), depending what was actually meant by that vague `fixme:type`) (because, in practice, that works way better than `shop=party;confectionery;pastry` which is another alternative I've seen)

**Comment by matkoniecz** [comment]
> I fail to see how searching for one string is harder then searching for another string?

1) if you already have support for `shop=yes` then adding support for also other tags is greater effort than not doing anything

2) much bigger problem is at fixing stage as `amenity=fixme` is not only for shop-like POIs where someone was unable to find preset. It is mix of all possible mapping issues where ED was insufficient to solve problem.

**Comment by matkoniecz** [comment]
it looks like at least some users are confused, see https://www.openstreetmap.org/changeset/145112033

> Good find. I made this edit with everydoor so it must have been a bug. I don’t remember what shop it is now.

**Comment by talllguy** [comment]
> some users are confused

That was my edit. When Mateseuz wrote on the changeset I had to rack my brain as to what that "mend" might have been. Everydoor is solid and is my go to 'I am near shops and have a few minutes to kill'. I truely appreciate the work on it.

However, this particular feature does feel a little wonky. I like how StreetComplete interprets notes by linking to a node within the node. That gives a little context. That said, I still don't remember how I managed to make that update.

Cheers!

**Comment by doniks** [comment]
Is there an overview of when this gets created? Which specific actions in ED lead to this? Might help with avoiding it, suggesting alternatives and improving existing fixme's

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/changeset/159980372 has analysis how such tagging may be applied

**Comment by LongNamedLoser** [comment]
Whenever I use  `shop=yes` tag, it is because I don't have enough information to conclude what shop it is. As @matkoniecz mentioned the tag is vague but that is due to a lack of info

Tools like StreetComplete, SCEE, Etc... allow me (or others) to then go out and add details later on

I find myself having to click on `shop=anime`, then manually change that to a `shop=yes` to avoid having to create a fixme that can't be easily expanded upon in the future

**Comment by Zverik** [comment]
Regarding the location of the note, Every Door keeps the exact location where an amenity was created, so there's nothing I can do. I assume mappers were creating things at their own location, that is, they haven't dragged markers toward the actual locations of shops. That's why most notes and objects are located on streets.

For that note, I can see how it's confusing. But also it indicates that a pharmacy is indeed somewhere around, and we have the name. I have found it [on Google Maps](https://maps.app.goo.gl/7uVYThYXxKP4bJWx7), albeit a hundred meters away. So idk. To me, some info is better than no info, and with Every Door, it would be easier to fix by the next experienced mapper in the area, than to add from scratch.

But yeah, I would prefer more guidance and tutoring from the mapping event organizers.
